# Database Configuration Examples
# Choose the appropriate configuration for your application framework

# Ruby on Rails (database.yml)
development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 25
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  # Enable connection pooling and optimization for production
  prepared_statements: true
  statement_timeout: 30000
  connect_timeout: 10