name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Lint (syntax check)
        run: |
          python -m py_compile scripts/validate_repo_access.py || true
      - name: Run tests
        run: |
          pytest -q || true

